import type { RelationType } from "../types";
import { SHARED_GROUP_NAME_MAX_LENGTH } from "./sharedConfig";

export const EMPTY_MESSAGES = {
  noData: "データなし",
  noDataYet: "まだデータがありません",
  noPhonetic: "発音記号なし",
  noResults: "該当する単語がありません",
} as const;

/** 最長想定:「ややこしい単語：delightful / delighted」と同程度（30 文字） */
export const GROUP_NAME_MAX_LENGTH = SHARED_GROUP_NAME_MAX_LENGTH;

export const RELATION_TYPE_LABELS: Record<RelationType, string> = {
  synonym: "類義語",
  antonym: "対義語",
  confusable: "紛らわしい語",
  cognate: "同語源",
};

export const LANGUAGE_OPTIONS = [
  { code: "LL.", name: "後期ラテン語" },
  { code: "ML.", name: "中世ラテン語" },
  { code: "NL.", name: "新ラテン語（略）" },
  { code: "VL.", name: "俗ラテン語" },
  { code: "af", name: "アフリカーンス語" },
  { code: "alv-gbe-pro", name: "ゲベ祖語" },
  { code: "ang", name: "古英語" },
  { code: "ar", name: "アラビア語" },
  { code: "ca", name: "カタルーニャ語" },
  { code: "cel", name: "ケルト語派" },
  { code: "cel-gau", name: "ガリア語" },
  { code: "cel-pro", name: "ケルト祖語" },
  { code: "cs", name: "チェコ語" },
  { code: "da", name: "デンマーク語" },
  { code: "de", name: "ドイツ語" },
  { code: "dum", name: "中期オランダ語" },
  { code: "egy", name: "エジプト語" },
  { code: "el", name: "現代ギリシャ語" },
  { code: "en", name: "英語" },
  { code: "enm", name: "中英語" },
  { code: "es", name: "スペイン語" },
  { code: "ett", name: "エトルリア語" },
  { code: "fa", name: "ペルシャ語" },
  { code: "fi", name: "フィンランド語" },
  { code: "fr", name: "フランス語" },
  { code: "frk", name: "フランク語" },
  { code: "frm", name: "中期フランス語" },
  { code: "fro", name: "古フランス語" },
  { code: "fro-nor", name: "古ノルマン・フランス語" },
  { code: "ga", name: "アイルランド語" },
  { code: "gem", name: "ゲルマン語派" },
  { code: "gem-pro", name: "ゲルマン祖語" },
  { code: "gmh", name: "中高ドイツ語" },
  { code: "gml", name: "中低ドイツ語" },
  { code: "gmq", name: "北ゲルマン語派" },
  { code: "gmq-oda", name: "古デンマーク語" },
  { code: "gmq-pro", name: "北ゲルマン祖語" },
  { code: "gmw-pro", name: "西ゲルマン祖語" },
  { code: "goh", name: "古高ドイツ語" },
  { code: "grc", name: "古代ギリシャ語" },
  { code: "hi", name: "ヒンディー語" },
  { code: "hit", name: "ヒッタイト語" },
  { code: "hu", name: "ハンガリー語" },
  { code: "ine-pro", name: "印欧祖語" },
  { code: "it", name: "イタリア語" },
  { code: "itc-pro", name: "イタリック祖語" },
  { code: "ja", name: "日本語" },
  { code: "ka", name: "ジョージア語" },
  { code: "ko", name: "韓国語" },
  { code: "la", name: "ラテン語" },
  { code: "la-lat", name: "後期ラテン語" },
  { code: "la-med", name: "中世ラテン語" },
  { code: "la-new", name: "新ラテン語" },
  { code: "la-vul", name: "俗ラテン語" },
  { code: "map-pro", name: "オーストロネシア祖語" },
  { code: "mga", name: "中期アイルランド語" },
  { code: "nds", name: "低地ドイツ語" },
  { code: "nl", name: "オランダ語" },
  { code: "no", name: "ノルウェー語" },
  { code: "non", name: "古ノルド語" },
  { code: "odt", name: "古オランダ語" },
  { code: "osp", name: "古スペイン語" },
  { code: "osx", name: "古ザクセン語" },
  { code: "ota", name: "オスマン・トルコ語" },
  { code: "pi", name: "パーリ語" },
  { code: "pl", name: "ポーランド語" },
  { code: "poz-pro", name: "マレー・ポリネシア祖語" },
  { code: "pro", name: "古プロヴァンス語" },
  { code: "pt", name: "ポルトガル語" },
  { code: "qsb-grc", name: "古代ギリシャ語基層" },
  { code: "roa-pro", name: "ロマンス祖語" },
  { code: "rom", name: "ロマニ語" },
  { code: "ru", name: "ロシア語" },
  { code: "sa", name: "サンスクリット語" },
  { code: "sco", name: "スコットランド語" },
  { code: "sga", name: "古アイルランド語" },
  { code: "sv", name: "スウェーデン語" },
  { code: "tr", name: "トルコ語" },
  { code: "trk-pro", name: "テュルク祖語" },
  { code: "wo", name: "ウォロフ語" },
  { code: "xno", name: "アングロ・ノルマン語" },
  { code: "yo", name: "ヨルバ語" },
  { code: "zh", name: "中国語" },
] as const;

export const ETYMOLOGY_RELATION_OPTIONS = [
  { value: "inh", label: "inh（継承）", description: "祖先言語から自然に受け継いだ語" },
  { value: "bor", label: "bor（借用）", description: "他言語から取り入れた語" },
  { value: "der", label: "der（派生）", description: "間接的な由来関係の語" },
] as const;

export const POS_OPTIONS = [
  { value: "名詞 noun", label: "名詞 noun" },
  { value: "動詞 verb", label: "動詞 verb" },
  { value: "形容詞 adjective", label: "形容詞 adjective" },
  { value: "副詞 adverb", label: "副詞 adverb" },
] as const;

export const INFLECTION_LABELS: Record<string, string> = {
  third_person_singular: "三単現",
  present_participle: "現在分詞",
  past_tense: "過去形",
  past_participle: "過去分詞",
  plural: "複数形",
  comparative: "比較級",
  superlative: "最上級",
  possessive: "所有格",
  inflection: "活用形",
};
