declare const __SHARED_GROUP_NAME_MAX_LENGTH__: number;
declare const __SHARED_API_BASE_URL_DEFAULT__: string;

export const SHARED_GROUP_NAME_MAX_LENGTH = __SHARED_GROUP_NAME_MAX_LENGTH__;
export const SHARED_API_BASE_URL_DEFAULT = __SHARED_API_BASE_URL_DEFAULT__;
